django_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("pages.urls")),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

pages/urls.py
from django.urls import path

from .views import HomePageView, AboutPageView

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("about/", AboutPageView.as_view(), name="about"),
]

snack/urls.py
from django.urls import path
from .views import HomePageView, AboutPageView

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("about/", AboutPageView.as_view(), name="about"),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    pass

    def __str__(self):
        return self.email

snack/models.py
from django.db import models
from django.contrib.auth import get_user_model

# Create your models here.
class Snack(models.Model):
    name = models.CharField(max_length=64)
    purchaser = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    description = models.TextField()




    def __str__(self):
        return self.name

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ('email', 'username',)

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('email', 'username',)

accounts/views.py
from django.shortcuts import render

# Create your views here.

snack/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView, HomePageView, AboutPageView
from .models import Snack




class HomePageView(HomePageView):
    template_name = "snack/home.html"
    model = Snack
    context_object_name = 'Home_snack_tracking_project'

class AboutPageView(AboutPageView):
    template_name = "snack/about.html"
    model = Snack

class SnackListView(ListView):
    template_name = 'snack/list.html'
    model = Snack
    context_object_name = 'snack_tracking_project'

class SnackDetailView(DetailView):
    template_name = 'snack_detail.html'
    model = Snack
    context_object_name = 'detail_snack_tracking_project'
    
class SnackCreateView(CreateView):
    model = Snack
    template_name = 'snacks/snack_create.html'
    fields = ['title', 'purchaser', 'description']

class SnackUpdateView(UpdateView):
    model = Snack
    template_name = 'snacks/snack_update.html'
    fields = ['title', 'purchaser', 'description']

class SnackDeleteView(DeleteView):
    model = Snack
    template_name = 'snacks/snack_delete.html'
    success_url = '/'

templates/403_csrf.html
{% extends '_base.html' %}

{% block title %}Forbidden (403){% endblock title %}

{% block content %}
<h1>Forbidden (403)</h1>
<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
  <title>{% block title %}DjangoX{% endblock title %}</title>
  <meta name="description" content="A framework for launching new Django projects quickly.">
  <meta name="author" content="">
  <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">

  {% block css %}
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static 'css/base.css' %}">
  {% endblock %}
</head>

<body>
  <header class="p-3 mb-3 border-bottom">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap">
            <use xlink:href="#bootstrap" />
          </svg>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="{% url 'home' %}" class="nav-link px-2 link-secondary">Home</a></li>
          <li><a href="{% url 'about' %}" class="nav-link px-2 link-dark">About</a></li>
        </ul>

        <div class="dropdown text-end">
          {% if user.is_authenticated %}
          <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" data-bs-toggle="dropdown"
            aria-expanded="false">
            {{ user.email }}
          </a>
          <ul class="dropdown-menu text-small">
            <li><a class="dropdown-item" href="{% url 'account_change_password' %}">Change password</a></li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li><a class="dropdown-item" href="{% url 'account_logout' %}">Sign out</a></li>
          </ul>
          {% else %}
          <form class="form-inline ml-auto">
            <a href="{% url 'account_login' %}" class="btn btn-outline-secondary">Log in</a>
            <a href="{% url 'account_signup' %}" class="btn btn-primary ml-2">Sign up</a>
          </form>
          {% endif %}
        </div>
      </div>
    </div>
  </header>

  <div class="container">
    {% block content %}
    <p>Default content...</p>
    {% endblock content %}
  </div>

  <footer class="footer">
    <div class="container">
      <span class="text-muted">Footer...</span>
    </div>
  </footer>

  {% block javascript %}
  <!-- Bootstrap JavaScript -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
    crossorigin="anonymous"></script>

  <!-- Project JS -->
  <script src="{% static 'js/base.js' %}"></script>

  {% endblock javascript %}

</body>

</html>

templates/pages/about.html
{% extends '_base.html' %}

{% block title %}About page{% endblock %}

{% block content %}
<h1>About page</h1>
{% endblock content %}

templates/pages/home.html
{% extends '_base.html' %}
{% load static %}

{% block title %}Home page{% endblock title %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <img src="{% static 'images/logo.png' %}" class="img-fluid" alt="DjangoX logo"/>
  <p class="lead">A Django starter project with batteries.</p>
</div>
{% endblock content %}

templates/snack_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Snacks Application</title>
</head>
<body>
    <nav>
        <a href="{% url 'snack_list' %}">List Snack</a> |
        <a href="{% url 'snack_create' %}">Create Snack</a>
        <a href="{% url 'snack_delete' %}">Delete Snack</a> |
        <a href="{% url 'snack_detail' %}">Detail Snack</a>
        <a href="{% url 'snack_update' %}">Update Snack</a>
    </nav>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

templates/snack_create.html
{% extends 'snack_base.html' %}

{% block content %}
<!-- Your custom HTML code goes here -->
{% endblock %}

templates/snack_delete.html
{% extends 'snack_base.html' %}

{% block content %}
<!-- Your custom HTML code goes here -->
{% endblock %}

templates/snack_detail.html
{% extends 'snack_base.html' %}

{% block content %}
<!-- Your custom HTML code goes here -->
{% endblock %}

templates/snack_list.html
{% extends 'snack_base.html' %}

{% block content %}
    <h1>Snacks</h1>
    <ul>
        {% for snack in snack_crud_project %}
            <li><a href="{% url 'snack_detail' pk=snack.pk %}">{{ snack.name }}, {{ snacks.description }}</a></li>
        {% empty %}
            <li>No snacks yet.</li>
        {% endfor %}
    </ul>
{% endblock %}



<!-- # Below from snacks-models  -->

<!-- {% extends 'base.html' %}

{%  block content %}

  {% for snacks in snacks_tracking_project %}
  <h2><a href="{% url 'snacks_detail' snacks.pk %}">{{ snacks.name }} , {{ snacks.description }}</a></h2>
{% endfor %}

{%  endblock content %} -->

templates/snack_update.html
{% extends 'snack_base.html' %}

{% block content %}
<!-- Your custom HTML code goes here -->
{% endblock %}